from datetime import datetime
from typing import Optional


def create_decision_record(
    title: str,
    context: str,
    decision: str,
    consequences: str = "",
    participants: Optional[list[str]] = None,
    date: Optional[str] = None,
) -> dict:
    """
    Generate a structured Architecture Decision Record (ADR) in Markdown format.

    Returns a dict with:
      - type: "decision_record"
      - markdown: the formatted ADR document
      - metadata: structured decision info
    """
    record_date = date or datetime.now().strftime("%Y-%m-%d")
    participant_list = participants or ["Not specified"]

    markdown = f"""# Decision Record: {title}

**Date:** {record_date}
**Status:** Accepted
**Participants:** {", ".join(participant_list)}

---

## Context

{context}

## Decision

{decision}

## Consequences

{consequences if consequences else "To be evaluated."}

---

*This decision record was automatically generated by Meeting Agent.*
"""

    return {
        "type": "decision_record",
        "markdown": markdown,
        "metadata": {
            "title": title,
            "date": record_date,
            "participants": participant_list,
            "context": context,
            "decision": decision,
            "consequences": consequences,
        },
    }
