from datetime import datetime
from typing import Optional


def create_report(
    title: str,
    summary: str,
    key_points: list[str],
    action_items: list[str],
    attendees: Optional[list[str]] = None,
    date: Optional[str] = None,
) -> dict:
    """
    Generate a structured meeting report in Markdown format.

    Returns a dict with:
      - type: "report"
      - markdown: the formatted meeting report
      - metadata: structured report info
    """
    report_date = date or datetime.now().strftime("%Y-%m-%d")
    attendee_list = attendees or ["Not specified"]

    key_points_md = "\n".join(f"- {point}" for point in key_points)
    action_items_md = "\n".join(f"- [ ] {item}" for item in action_items)
    attendees_md = "\n".join(f"- {name}" for name in attendee_list)

    markdown = f"""# Meeting Report: {title}

**Date:** {report_date}

---

## Attendees

{attendees_md}

## Executive Summary

{summary}

## Key Discussion Points

{key_points_md}

## Action Items

{action_items_md}

---

*This report was automatically generated by Meeting Agent.*
"""

    return {
        "type": "report",
        "markdown": markdown,
        "metadata": {
            "title": title,
            "date": report_date,
            "summary": summary,
            "key_points": key_points,
            "action_items": action_items,
            "attendees": attendee_list,
        },
    }
